### ISSUE TITLE
native_dio_adapter

### ISSUE THREAD

**Issue by vanyasem** [CQLabs/homebrew-dcm#1]
Currently DCM ignores system-wide proxy settings on macOS, which poses a problem for users behind strict corporate firewalls

To solve this issue, you need to add https://pub.dev/packages/native_dio_adapter to your Dio initialisation code, which would in turn depend on [cupertino_http](https://pub.dev/packages/cupertino_http) package that respects system-wide proxy settings out of the box

**Comment by incendial** [comment]
For any further bug reports please use our Discord channel https://discord.gg/Vzjprgk4sb

Closing this, but I'll take a look.
